# Configure the ipt_NETFLOW module config

config_vars = node['ipt-netflow']['config'].select{|k, v| v}

config_vars.each do |k, v|
  sysctl_param "net.netflow.#{k}" do
    value v
  end
end

#config_string = config_vars.map{|k, v| "#{k}=#{v}"}.join(" ")
#
#file "/etc/modprobe.d/ipt_NETFLOW.conf" do
#  content %{# Generated by Chef
#options ipt_NETFLOW #{config_string}
#  }
#end

file "/etc/modules-load.d/ipt_NETFLOW.conf" do
  content %{# Generated by Chef
ipt_NETFLOW
  }
end
